#!/usr/bin/env bash
# Simulator-only visual evidence. Does not exercise Bluetooth or device authentication.
set -Eeuo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IOS_BUILD_DIR="$PROJECT_ROOT/build/ios"
LOG_DIR="$IOS_BUILD_DIR/logs"
SCREENSHOT_DIR="$IOS_BUILD_DIR/screenshots"
mkdir -p "$LOG_DIR" "$SCREENSHOT_DIR"
exec > >(tee "$LOG_DIR/capture-ios-ui.log") 2>&1

if [[ "$(uname -s)" != Darwin ]]; then
  printf '%s\n' 'UI capture requires macOS with Xcode and an available iPhone Simulator.' >&2
  exit 1
fi

export DEVELOPER_DIR="${DEVELOPER_DIR:-/Applications/Xcode_16.4.app/Contents/Developer}"
export CARGO_TARGET_DIR="$PROJECT_ROOT/target"
export IPHONEOS_DEPLOYMENT_TARGET=17.0
RUST_TOOLCHAIN=1.98.1
BUNDLE_ID=org.band9lab.diagnostics
PROJECT_PATH="$PROJECT_ROOT/ios/Band9Diagnostics.xcodeproj"
DEVICE_IPA="$IOS_BUILD_DIR/Band9Diagnostics-unsigned.ipa"
DEVICE_LIBRARY="$PROJECT_ROOT/ios/Vendor/libband9_ffi.a"
SIMULATOR_BUILD_DIR="$IOS_BUILD_DIR/simulator-derived-data"
SIMULATOR_APP="$SIMULATOR_BUILD_DIR/Build/Products/Release-iphonesimulator/Band9Diagnostics.app"

# Leave a margin inside the CI step's eight-minute limit. Every external build,
# boot and capture command shares this total budget, including process cleanup.
CAPTURE_DEADLINE=$((SECONDS + 450))
run_bounded() {
  local remaining=$((CAPTURE_DEADLINE - SECONDS))
  if (( remaining <= 0 )); then
    printf '%s\n' 'Simulator UI capture exceeded its total time budget.' >&2
    return 124
  fi
  python3 -c '
import os
import signal
import subprocess
import sys

process = subprocess.Popen(sys.argv[2:], start_new_session=True)
try:
    result = process.wait(timeout=int(sys.argv[1]))
except subprocess.TimeoutExpired:
    os.killpg(process.pid, signal.SIGTERM)
    try:
        process.wait(timeout=3)
    except subprocess.TimeoutExpired:
        os.killpg(process.pid, signal.SIGKILL)
        process.wait()
    print("Simulator UI capture exceeded its total time budget.", file=sys.stderr)
    sys.exit(124)
sys.exit(result if result >= 0 else 128 - result)
' "$remaining" "$@"
}

[[ -d "$DEVELOPER_DIR" && -d "$PROJECT_PATH" ]]
[[ -f "$DEVICE_IPA" && -f "$DEVICE_LIBRARY" ]]
DEVICE_IPA_HASH="$(shasum -a 256 "$DEVICE_IPA" | awk '{print $1}')"
DEVICE_LIBRARY_HASH="$(shasum -a 256 "$DEVICE_LIBRARY" | awk '{print $1}')"

check_device_artifacts() {
  [[ "$(shasum -a 256 "$DEVICE_IPA" | awk '{print $1}')" == "$DEVICE_IPA_HASH" ]] &&
    [[ "$(shasum -a 256 "$DEVICE_LIBRARY" | awk '{print $1}')" == "$DEVICE_LIBRARY_HASH" ]]
}
finish() {
  local result=$?
  trap - EXIT
  if ! check_device_artifacts; then
    printf '%s\n' 'Device IPA or device Rust library changed during Simulator capture.' >&2
    result=1
  fi
  printf 'Simulator UI capture finished with exit status %s\n' "$result"
  exit "$result"
}
trap finish EXIT

SIMULATOR_ARCH="$(uname -m)"
case "$SIMULATOR_ARCH" in
  arm64) RUST_TARGET=aarch64-apple-ios-sim ;;
  x86_64) RUST_TARGET=x86_64-apple-ios ;;
  *) printf 'Unsupported Simulator host architecture: %s\n' "$SIMULATOR_ARCH" >&2; exit 1 ;;
esac

cd "$PROJECT_ROOT"
run_bounded rustup target add --toolchain "$RUST_TOOLCHAIN" "$RUST_TARGET"
SIMULATOR_SDK="$(xcrun --sdk iphonesimulator --show-sdk-path)"
SIMULATOR_SDK_VERSION="$(xcrun --sdk iphonesimulator --show-sdk-version)"
run_bounded env SDKROOT="$SIMULATOR_SDK" \
  cargo +"$RUST_TOOLCHAIN" build --package band9-ffi --release --target "$RUST_TARGET" --locked
SIMULATOR_LIBRARY_DIR="$CARGO_TARGET_DIR/$RUST_TARGET/release"
[[ -f "$SIMULATOR_LIBRARY_DIR/libband9_ffi.a" ]]

# Override the search path rather than replacing ios/Vendor's device archive.
# The project was already generated by build-ios.sh; no second XcodeGen build.
run_bounded xcodebuild \
  -project "$PROJECT_PATH" \
  -scheme Band9Diagnostics \
  -configuration Release \
  -sdk iphonesimulator \
  -destination 'generic/platform=iOS Simulator' \
  -derivedDataPath "$SIMULATOR_BUILD_DIR" \
  SUPPORTED_PLATFORMS=iphonesimulator \
  SDKROOT=iphonesimulator \
  ARCHS="$SIMULATOR_ARCH" \
  ONLY_ACTIVE_ARCH=YES \
  LIBRARY_SEARCH_PATHS="$SIMULATOR_LIBRARY_DIR" \
  CODE_SIGNING_ALLOWED=NO \
  CODE_SIGNING_REQUIRED=NO \
  CODE_SIGN_IDENTITY= \
  CURRENT_PROJECT_VERSION="${GITHUB_RUN_NUMBER:-1}" \
  build

[[ -f "$SIMULATOR_APP/Band9Diagnostics" ]]
run_bounded python3 - "$SIMULATOR_APP/Info.plist" <<'PY'
import plistlib
import sys
with open(sys.argv[1], "rb") as file:
    info = plistlib.load(file)
if info.get("CFBundleSupportedPlatforms") != ["iPhoneSimulator"]:
    raise SystemExit("Expected a separate iPhoneSimulator application")
if info.get("CFBundleIdentifier") != "org.band9lab.diagnostics":
    raise SystemExit("Unexpected Simulator application identifier")
PY

run_bounded xcrun simctl list devices available --json > "$LOG_DIR/available-simulators.json"
SIMULATOR_SELECTION="$(python3 - "$LOG_DIR/available-simulators.json" "$SIMULATOR_SDK_VERSION" <<'PY'
import json
import sys
with open(sys.argv[1], encoding="utf-8") as file:
    devices = json.load(file)["devices"]
candidates = []
sdk_version = tuple(map(int, sys.argv[2].split(".")))
for runtime, entries in devices.items():
    if ".iOS-" not in runtime:
        continue
    runtime_version = tuple(map(int, runtime.rsplit(".iOS-", 1)[1].split("-")))
    if not 17 <= runtime_version[0] <= sdk_version[0]:
        continue
    for device in entries:
        if device.get("isAvailable") and device["name"].startswith("iPhone"):
            candidates.append((runtime_version != sdk_version, device["name"] != "iPhone 16 Pro",
                               device["name"], device["udid"], device["state"]))
if not candidates:
    raise SystemExit("No available iPhone Simulator; UI capture cannot be verified")
_, _, name, udid, state = sorted(candidates)[0]
print(f"{udid}|{state}|{name}")
PY
)"
IFS='|' read -r SIMULATOR_ID SIMULATOR_STATE SIMULATOR_NAME <<< "$SIMULATOR_SELECTION"
printf 'Capturing %s on %s (%s)\n' "$BUNDLE_ID" "$SIMULATOR_NAME" "$SIMULATOR_ARCH"
if [[ "$SIMULATOR_STATE" != Booted ]]; then
  run_bounded xcrun simctl boot "$SIMULATOR_ID"
fi
run_bounded xcrun simctl bootstatus "$SIMULATOR_ID" -b
run_bounded xcrun simctl status_bar "$SIMULATOR_ID" override \
  --time '9:41' --batteryState charged --batteryLevel 100
run_bounded xcrun simctl install "$SIMULATOR_ID" "$SIMULATOR_APP"

for screen in watch:watch:0 gallery:watch:1 discover:watch:2 health:health:0 data:data:0; do
  IFS=: read -r image_name experience tab_index <<< "$screen"
  # simctl passes arguments after the bundle ID directly to the app. Foundation
  # reads -watch.experience from its argument domain before persistent defaults.
  launch_output="$(run_bounded xcrun simctl launch --terminate-running-process \
    "$SIMULATOR_ID" "$BUNDLE_ID" -watch.experience "$experience" -watch.tab "$tab_index")"
  printf '%s\n' "$launch_output"
  app_pid="$(printf '%s\n' "$launch_output" | awk '/: [0-9]+$/ {print $NF}' | tail -n 1)"
  [[ "$app_pid" =~ ^[0-9]+$ ]]
  run_bounded sleep 3
  # Simulator app processes run on the host. Fail instead of capturing SpringBoard
  # if the launched process crashed before its initial screen was rendered.
  kill -0 "$app_pid"
  run_bounded xcrun simctl io "$SIMULATOR_ID" screenshot --type=png "$SCREENSHOT_DIR/$image_name.png"
done

run_bounded python3 - "$SCREENSHOT_DIR" "$SIMULATOR_NAME" "$SIMULATOR_ARCH" <<'PY'
import hashlib
import json
import os
from pathlib import Path
import struct
import sys

directory = Path(sys.argv[1])
images = []
for name, experience, tab in (("watch", "watch", 0), ("gallery", "watch", 1),
                              ("discover", "watch", 2), ("health", "health", 0), ("data", "data", 0)):
    path = directory / f"{name}.png"
    data = path.read_bytes()
    if len(data) < 32 or data[:8] != b"\x89PNG\r\n\x1a\n" or data[12:16] != b"IHDR":
        raise SystemExit(f"Missing or invalid screenshot: {path.name}")
    width, height = struct.unpack_from(">II", data, 16)
    if width < 300 or height < 500:
        raise SystemExit(f"Unexpected screenshot size: {path.name}")
    images.append({"experience": experience, "tab": tab, "file": path.name, "width": width,
                   "height": height, "sha256": hashlib.sha256(data).hexdigest()})
record = {"verification": "Simulator UI capture only; no Bluetooth/authentication/device-data verification",
          "data": "Empty state; no private key, device identifier or health records imported",
          "simulator": sys.argv[2], "architecture": sys.argv[3],
          "source_commit": os.environ.get("GITHUB_SHA", "local"), "images": images}
(directory / "capture.json").write_text(json.dumps(record, indent=2) + "\n", encoding="utf-8")
print(json.dumps(record, indent=2))
PY

check_device_artifacts
if [[ -n "${GITHUB_STEP_SUMMARY:-}" ]]; then
  {
    printf '\n### Simulator UI screenshots\n\n'
    printf 'Captured watch, gallery, discover, health and data screens on %s.\n\n' "$SIMULATOR_NAME"
    printf '%s\n' 'These screenshots verify rendered Simulator UI only. Bluetooth, authentication and real health data were not exercised.'
    printf '%s\n' 'The unsigned device IPA and its Rust static library remained byte-for-byte unchanged.'
  } >> "$GITHUB_STEP_SUMMARY"
fi
